version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd app && npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  artifacts:
    files:
      - app/build/**/*
